# Generated by Django 5.1.1 on 2024-10-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pornstar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_link', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('eye_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('catigories', models.CharField(max_length=255)),
                ('relative_catigories', models.CharField(max_length=255)),
                ('isalive', models.BooleanField(default=True)),
            ],
        ),
    ]
