# Generated by Django 5.1.1 on 2024-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pornstars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pornstar',
            name='catigories',
            field=models.TextField(),
        ),
    ]
